pipeline {
agent any
stages(‘Build’) {
git ‘https://gitbub.com/your/project.git’
sh ‘mvn clean compile’
}
stages(‘Test’) {
steps {
sh ‘mvn test’
}
}
stages(‘Test’) {
steps {
sh ‘mvn test’
}
post {
always {
junit ‘**/target/surefire-reports/TEST-*xml’
}
}
}
}
